### ISSUE TITLE
APT whitelist request for libdiscid0

### ISSUE THREAD

**Issue by phw** [travis-ci/apt-package-whitelist#1022] opened 2015-08-27 10:03 UTC

**Comment by BanzaiMan** [comment] 2015-08-27 20:33
Duplicate of #1023.

**Closed by BanzaiMan** 2015-08-27 20:33 UTC
Labels: apt-whitelist-check-run

**Comment by phw** [comment] 2015-08-28 07:34
@BanzaiMan Something seems to be wrong with travisbot figuring out the package names. The development package is actually not called `libdiscid-dev` but `libdiscid0-dev`, see http://packages.ubuntu.com/precise/libdiscid0-dev 

I have filed a pull request #1053

Thanks for the fast merge and sorry for the duplicate, didn't know travisbot pulls in related packages.
