### ISSUE TITLE
APT whitelist request for shunit2

### ISSUE THREAD

**Issue by havenwood** [travis-ci/apt-package-whitelist#1425] opened 2015-10-18 21:17 UTC
We use [shUnit2](https://shunit2.googlecode.com/svn/trunk/source/2.1/doc/shunit2.html) for unit testing shell scripting (in [chruby](https://github.com/postmodern/chruby) and [ruby-install](https://github.com/postmodern/ruby-install)).

**Comment by BanzaiMan** [comment] 2015-10-19 17:52
Duplicate of #1371.

**Closed by BanzaiMan** 2015-10-19 17:52 UTC
Labels: apt-whitelist-check-run
