### ISSUE TITLE
APT whitelist request for qtlocation5-dev

### ISSUE THREAD

**Issue by tmpsantos** [travis-ci/apt-package-whitelist#2900] opened 2016-04-27 18:37 UTC
Needed for testing software using Qt5 and the QtLocation module.

The package is available by default on the Ubuntu Trusty bot.

http://doc.qt.io/qt-5/qtlocation-index.html

**Comment by BanzaiMan** [comment] 2016-05-01 05:31
Duplicate of #2899.

**Closed by BanzaiMan** 2016-05-01 05:31 UTC
Labels: apt-whitelist-check-run

**Comment by tmpsantos** [comment] 2016-05-02 08:54
> Duplicate of #2899.

They are not the same package.

**Comment by BanzaiMan** [comment] 2016-05-02 09:06
If you look at the PRs involved, you will see that they end up adding the same ones.

**Comment by tmpsantos** [comment] 2016-05-02 09:07
> If you look at the PRs involved, you will see that they end up adding the same ones.

Indeed, missed that. My apologies.
